# Generated by Django 3.2 on 2022-06-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='brend-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Bredns',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.CharField(choices=[('Строительный', 'Строительный'), ('Продукты', 'Продукты'), ('Текстильные', 'Текстильные')], max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='certificate-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='customers-images', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='products_informations_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='certificate-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='home-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главная Изображение',
                'verbose_name_plural': 'Главная Изображения',
            },
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(max_length=100, verbose_name='Куда')),
                ('price', models.CharField(max_length=64, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
            },
        ),
        migrations.CreateModel(
            name='PriceExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='price_excel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='seller-images', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-images', verbose_name='Изображение')),
                ('price_type', models.CharField(blank=True, choices=[('DOL', 'Dollar'), ('EUR', 'Eur'), ('RUB', 'Ruble')], max_length=64, null=True, verbose_name='Тип цены')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='ИД(Code)')),
                ('measurement_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Тип измерения')),
                ('mass', models.CharField(blank=True, max_length=64, null=True, verbose_name='Масса за 1 шт')),
                ('all_mass', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вес 1 коробки')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(blank=True, choices=[('NEW', 'New'), ('POP', 'Popular')], max_length=64, null=True, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('value1', models.CharField(blank=True, max_length=200, null=True)),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('value2', models.CharField(blank=True, max_length=100, null=True)),
                ('title3', models.CharField(blank=True, max_length=100, null=True)),
                ('value3', models.CharField(blank=True, max_length=200, null=True)),
                ('title4', models.CharField(blank=True, max_length=200, null=True)),
                ('value4', models.CharField(blank=True, max_length=100, null=True)),
                ('title5', models.CharField(blank=True, max_length=100, null=True)),
                ('value5', models.CharField(blank=True, max_length=200, null=True)),
                ('title6', models.CharField(blank=True, max_length=200, null=True)),
                ('value6', models.CharField(blank=True, max_length=100, null=True)),
                ('title7', models.CharField(blank=True, max_length=100, null=True)),
                ('value7', models.CharField(blank=True, max_length=200, null=True)),
                ('title8', models.CharField(blank=True, max_length=200, null=True)),
                ('value8', models.CharField(blank=True, max_length=100, null=True)),
                ('title9', models.CharField(blank=True, max_length=100, null=True)),
                ('value9', models.CharField(blank=True, max_length=200, null=True)),
                ('title10', models.CharField(blank=True, max_length=200, null=True)),
                ('value10', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='progress.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='progress.seller')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
