# Generated by Django 4.0.5 on 2022-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('NEW', 'New')], max_length=64, null=True, verbose_name='Тип'),
        ),
    ]
