# Generated by Django 3.2 on 2022-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='certificate-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'CatalogImage',
                'verbose_name_plural': 'CatalogImages',
            },
        ),
    ]
