# Generated by Django 3.2 on 2022-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_catalogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='description',
        ),
        migrations.AddField(
            model_name='brend',
            name='description',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
