# Generated by Django 4.0.5 on 2022-06-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_customer_seller_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='progress.seller'),
            preserve_default=False,
        ),
    ]
