# Generated by Django 4.0.5 on 2022-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_mass',
            field=models.CharField(default=1, max_length=64, verbose_name='Вес 1 коробки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=64, verbose_name='ИД(Code)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.CharField(default=1, max_length=64, verbose_name='Масса за 1 шт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(default=1, max_length=64, verbose_name='Тип измерения'),
            preserve_default=False,
        ),
    ]
