# Generated by Django 4.0.5 on 2022-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_product_all_mass_product_code_product_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
