# Generated by Django 4.0.5 on 2022-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
