# Generated by Django 4.0.5 on 2022-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
